name: GitHub Basic Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      # build and run unit tests
      - name: Setup Go 1.21.1
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.1'

      - name: Build images
        timeout-minutes: 10
        run: docker compose build

      - name: Run containers
        timeout-minutes: 5
        run: |
          docker compose up -d
          ./scripts/wait-for.sh -t 120 "http://localhost:8080/manage/health" -- echo "Host localhost:8080 is active"

      - name: Run Unit Tests
        run: |
          go test ./src/handler

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: "postman/[pgstart]Script_Execution_System.postman_collection.json"
          delayRequest: 100
          reporters: '[ "cli" ]'

      - name: Stop containers
        if: always()
        continue-on-error: true
        run: docker compose down -v